apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    path: app-of-apps
    repoURL: https://github.com/cavalcante001/descomplicando-gitops-no-kubernetes-argocd
    targetRevision: feat/day2
    helm:
      parameters:
        - name: argocd.giropopsSenhas.enabled
          value: "true"
        - name: argocd.randomloggerApp.enabled
          value: "true"
  destination:
    server: https://45.159.228.156:6443
    namespace: giropops-senhas
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=truegit 