apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  destination:
    namespace: grafana
    server: https://45.159.228.156:6443
  sources:
  - repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 7.0.19
    helm:
      valueFiles:
      - $values/grafana/values.yaml
  - repoURL: https://github.com/cavalcante001/descomplicando-gitops-no-kubernetes-argocd
    targetRevision: feat/day2
    ref: values