{{ if .Values.argocd.giropopsSenhas.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: giropops-senhas
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/cavalcante001/descomplicando-gitops-no-kubernetes-argocd
    targetRevision: feat/day2
    path: giropops-senhas/helm
  destination:
    server: https://45.159.228.156:6443
    namespace: giropops-senhas
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}